name: Build & deploy
on:
  push

jobs:
  build-linux-release:
    name: Build linux release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Build
        run: |
          cd alt-build && bash alt-release.sh
          cd ..
          mkdir dist
          cp ./out/Release/libnodev2.so dist/libnodev2.so

      - name: Build aarch64
        run: |
          sudo apt-get install cmake build-essential binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu python3 make python3-pip
          ln -s /usr/aarch64-linux-gnu/lib/ld-linux-aarch64.so.1 /lib/ld-linux-aarch64.so.1
          chmod +rwx alt-build/alt-release-aarch64.sh
          cd alt-build && bash alt-release-aarch64.sh
          cd ..
          mkdir dist_aarch64
          cp ./out/Release/libnodev2.so dist_aarch64/libnodev2.so

      - uses: actions/upload-artifact@v3
        with:
          name: node-linux-release
          path: ./dist/

      - uses: actions/upload-artifact@v3
        with:
          name: node-linux-release-aarch64
          path: ./dist_aarch64/